/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as OperacaoRouteImport } from './routes/operacao'
import { Route as CozinhaRouteImport } from './routes/cozinha'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SucessoIdRouteImport } from './routes/sucesso.$id'
import { Route as PedidosNovoRouteImport } from './routes/pedidos.novo'
import { Route as PedidosTokenRouteImport } from './routes/pedidos.$token'
import { Route as PagarIdRouteImport } from './routes/pagar.$id'
import { Route as ApiDisponibilidadeRouteImport } from './routes/api/disponibilidade'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ApiPublicMpPreferenceRouteImport } from './routes/api/public/mp-preference'
import { Route as ApiPublicMetaCapiRouteImport } from './routes/api/public/meta-capi'
import { Route as ApiPedidosEditarPorTokenRouteImport } from './routes/api/pedidos/editar-por-token'
import { Route as ApiOperacaoTokenRouteImport } from './routes/api/operacao/token'
import { Route as ApiOperacaoPedidosRouteImport } from './routes/api/operacao/pedidos'
import { Route as ApiCozinhaTokenRouteImport } from './routes/api/cozinha/token'
import { Route as ApiCozinhaPedidosRouteImport } from './routes/api/cozinha/pedidos'
import { Route as ApiAdminSaveConfigRouteImport } from './routes/api/admin/save-config'
import { Route as ApiAdminPedidosRouteImport } from './routes/api/admin/pedidos'
import { Route as ApiAdminOperatorsRouteImport } from './routes/api/admin/operators'
import { Route as ApiAdminOperacaoUsersRouteImport } from './routes/api/admin/operacao-users'
import { Route as ApiAdminEmailLogsRouteImport } from './routes/api/admin/email-logs'
import { Route as ApiAdminEmailRouteImport } from './routes/api/admin/email'
import { Route as ApiAdminCuponsRouteImport } from './routes/api/admin/cupons'
import { Route as ApiAdminCozinhaUsersRouteImport } from './routes/api/admin/cozinha-users'
import { Route as ApiAdminConciliarAsaasRouteImport } from './routes/api/admin/conciliar-asaas'
import { Route as ApiAdminConciliacaoPendenciasRouteImport } from './routes/api/admin/conciliacao-pendencias'
import { Route as ApiAdminArquivarPedidosRouteImport } from './routes/api/admin/arquivar-pedidos'
import { Route as ApiPublicPedidoIdRouteImport } from './routes/api/public/pedido.$id'
import { Route as ApiPublicPagamentoIdRouteImport } from './routes/api/public/pagamento.$id'
import { Route as ApiPublicCupomValidarRouteImport } from './routes/api/public/cupom/validar'
import { Route as ApiPublicComprovanteIdRouteImport } from './routes/api/public/comprovante.$id'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas/webhook'
import { Route as ApiPublicAsaasChargeRouteImport } from './routes/api/public/asaas/charge'
import { Route as ApiPublicAdminPedidosRouteImport } from './routes/api/public/admin/pedidos'
import { Route as ApiPublicAsaasStatusIdRouteImport } from './routes/api/public/asaas/status.$id'

const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CozinhaRoute = CozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoIdRoute = SucessoIdRouteImport.update({
  id: '/sucesso/$id',
  path: '/sucesso/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosNovoRoute = PedidosNovoRouteImport.update({
  id: '/pedidos/novo',
  path: '/pedidos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosTokenRoute = PedidosTokenRouteImport.update({
  id: '/pedidos/$token',
  path: '/pedidos/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarIdRoute = PagarIdRouteImport.update({
  id: '/pagar/$id',
  path: '/pagar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisponibilidadeRoute = ApiDisponibilidadeRouteImport.update({
  id: '/api/disponibilidade',
  path: '/api/disponibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMpPreferenceRoute = ApiPublicMpPreferenceRouteImport.update({
  id: '/api/public/mp-preference',
  path: '/api/public/mp-preference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaCapiRoute = ApiPublicMetaCapiRouteImport.update({
  id: '/api/public/meta-capi',
  path: '/api/public/meta-capi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPedidosEditarPorTokenRoute =
  ApiPedidosEditarPorTokenRouteImport.update({
    id: '/api/pedidos/editar-por-token',
    path: '/api/pedidos/editar-por-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOperacaoTokenRoute = ApiOperacaoTokenRouteImport.update({
  id: '/api/operacao/token',
  path: '/api/operacao/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperacaoPedidosRoute = ApiOperacaoPedidosRouteImport.update({
  id: '/api/operacao/pedidos',
  path: '/api/operacao/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCozinhaTokenRoute = ApiCozinhaTokenRouteImport.update({
  id: '/api/cozinha/token',
  path: '/api/cozinha/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCozinhaPedidosRoute = ApiCozinhaPedidosRouteImport.update({
  id: '/api/cozinha/pedidos',
  path: '/api/cozinha/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSaveConfigRoute = ApiAdminSaveConfigRouteImport.update({
  id: '/api/admin/save-config',
  path: '/api/admin/save-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPedidosRoute = ApiAdminPedidosRouteImport.update({
  id: '/api/admin/pedidos',
  path: '/api/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOperatorsRoute = ApiAdminOperatorsRouteImport.update({
  id: '/api/admin/operators',
  path: '/api/admin/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOperacaoUsersRoute = ApiAdminOperacaoUsersRouteImport.update({
  id: '/api/admin/operacao-users',
  path: '/api/admin/operacao-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailLogsRoute = ApiAdminEmailLogsRouteImport.update({
  id: '/api/admin/email-logs',
  path: '/api/admin/email-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailRoute = ApiAdminEmailRouteImport.update({
  id: '/api/admin/email',
  path: '/api/admin/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCuponsRoute = ApiAdminCuponsRouteImport.update({
  id: '/api/admin/cupons',
  path: '/api/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCozinhaUsersRoute = ApiAdminCozinhaUsersRouteImport.update({
  id: '/api/admin/cozinha-users',
  path: '/api/admin/cozinha-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConciliarAsaasRoute = ApiAdminConciliarAsaasRouteImport.update({
  id: '/api/admin/conciliar-asaas',
  path: '/api/admin/conciliar-asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConciliacaoPendenciasRoute =
  ApiAdminConciliacaoPendenciasRouteImport.update({
    id: '/api/admin/conciliacao-pendencias',
    path: '/api/admin/conciliacao-pendencias',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminArquivarPedidosRoute = ApiAdminArquivarPedidosRouteImport.update({
  id: '/api/admin/arquivar-pedidos',
  path: '/api/admin/arquivar-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPedidoIdRoute = ApiPublicPedidoIdRouteImport.update({
  id: '/api/public/pedido/$id',
  path: '/api/public/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPagamentoIdRoute = ApiPublicPagamentoIdRouteImport.update({
  id: '/api/public/pagamento/$id',
  path: '/api/public/pagamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCupomValidarRoute = ApiPublicCupomValidarRouteImport.update({
  id: '/api/public/cupom/validar',
  path: '/api/public/cupom/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicComprovanteIdRoute = ApiPublicComprovanteIdRouteImport.update({
  id: '/api/public/comprovante/$id',
  path: '/api/public/comprovante/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas/webhook',
  path: '/api/public/asaas/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasChargeRoute = ApiPublicAsaasChargeRouteImport.update({
  id: '/api/public/asaas/charge',
  path: '/api/public/asaas/charge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminPedidosRoute = ApiPublicAdminPedidosRouteImport.update({
  id: '/api/public/admin/pedidos',
  path: '/api/public/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasStatusIdRoute = ApiPublicAsaasStatusIdRouteImport.update({
  id: '/api/public/asaas/status/$id',
  path: '/api/public/asaas/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cozinha': typeof CozinhaRoute
  '/operacao': typeof OperacaoRoute
  '/pedido': typeof PedidoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/disponibilidade': typeof ApiDisponibilidadeRoute
  '/pagar/$id': typeof PagarIdRoute
  '/pedidos/$token': typeof PedidosTokenRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/sucesso/$id': typeof SucessoIdRoute
  '/api/admin/arquivar-pedidos': typeof ApiAdminArquivarPedidosRoute
  '/api/admin/conciliacao-pendencias': typeof ApiAdminConciliacaoPendenciasRoute
  '/api/admin/conciliar-asaas': typeof ApiAdminConciliarAsaasRoute
  '/api/admin/cozinha-users': typeof ApiAdminCozinhaUsersRoute
  '/api/admin/cupons': typeof ApiAdminCuponsRoute
  '/api/admin/email': typeof ApiAdminEmailRoute
  '/api/admin/email-logs': typeof ApiAdminEmailLogsRoute
  '/api/admin/operacao-users': typeof ApiAdminOperacaoUsersRoute
  '/api/admin/operators': typeof ApiAdminOperatorsRoute
  '/api/admin/pedidos': typeof ApiAdminPedidosRoute
  '/api/admin/save-config': typeof ApiAdminSaveConfigRoute
  '/api/cozinha/pedidos': typeof ApiCozinhaPedidosRoute
  '/api/cozinha/token': typeof ApiCozinhaTokenRoute
  '/api/operacao/pedidos': typeof ApiOperacaoPedidosRoute
  '/api/operacao/token': typeof ApiOperacaoTokenRoute
  '/api/pedidos/editar-por-token': typeof ApiPedidosEditarPorTokenRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/mp-preference': typeof ApiPublicMpPreferenceRoute
  '/api/public/admin/pedidos': typeof ApiPublicAdminPedidosRoute
  '/api/public/asaas/charge': typeof ApiPublicAsaasChargeRoute
  '/api/public/asaas/webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/comprovante/$id': typeof ApiPublicComprovanteIdRoute
  '/api/public/cupom/validar': typeof ApiPublicCupomValidarRoute
  '/api/public/pagamento/$id': typeof ApiPublicPagamentoIdRoute
  '/api/public/pedido/$id': typeof ApiPublicPedidoIdRoute
  '/api/public/asaas/status/$id': typeof ApiPublicAsaasStatusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cozinha': typeof CozinhaRoute
  '/operacao': typeof OperacaoRoute
  '/pedido': typeof PedidoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/disponibilidade': typeof ApiDisponibilidadeRoute
  '/pagar/$id': typeof PagarIdRoute
  '/pedidos/$token': typeof PedidosTokenRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/sucesso/$id': typeof SucessoIdRoute
  '/api/admin/arquivar-pedidos': typeof ApiAdminArquivarPedidosRoute
  '/api/admin/conciliacao-pendencias': typeof ApiAdminConciliacaoPendenciasRoute
  '/api/admin/conciliar-asaas': typeof ApiAdminConciliarAsaasRoute
  '/api/admin/cozinha-users': typeof ApiAdminCozinhaUsersRoute
  '/api/admin/cupons': typeof ApiAdminCuponsRoute
  '/api/admin/email': typeof ApiAdminEmailRoute
  '/api/admin/email-logs': typeof ApiAdminEmailLogsRoute
  '/api/admin/operacao-users': typeof ApiAdminOperacaoUsersRoute
  '/api/admin/operators': typeof ApiAdminOperatorsRoute
  '/api/admin/pedidos': typeof ApiAdminPedidosRoute
  '/api/admin/save-config': typeof ApiAdminSaveConfigRoute
  '/api/cozinha/pedidos': typeof ApiCozinhaPedidosRoute
  '/api/cozinha/token': typeof ApiCozinhaTokenRoute
  '/api/operacao/pedidos': typeof ApiOperacaoPedidosRoute
  '/api/operacao/token': typeof ApiOperacaoTokenRoute
  '/api/pedidos/editar-por-token': typeof ApiPedidosEditarPorTokenRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/mp-preference': typeof ApiPublicMpPreferenceRoute
  '/api/public/admin/pedidos': typeof ApiPublicAdminPedidosRoute
  '/api/public/asaas/charge': typeof ApiPublicAsaasChargeRoute
  '/api/public/asaas/webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/comprovante/$id': typeof ApiPublicComprovanteIdRoute
  '/api/public/cupom/validar': typeof ApiPublicCupomValidarRoute
  '/api/public/pagamento/$id': typeof ApiPublicPagamentoIdRoute
  '/api/public/pedido/$id': typeof ApiPublicPedidoIdRoute
  '/api/public/asaas/status/$id': typeof ApiPublicAsaasStatusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cozinha': typeof CozinhaRoute
  '/operacao': typeof OperacaoRoute
  '/pedido': typeof PedidoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/disponibilidade': typeof ApiDisponibilidadeRoute
  '/pagar/$id': typeof PagarIdRoute
  '/pedidos/$token': typeof PedidosTokenRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/sucesso/$id': typeof SucessoIdRoute
  '/api/admin/arquivar-pedidos': typeof ApiAdminArquivarPedidosRoute
  '/api/admin/conciliacao-pendencias': typeof ApiAdminConciliacaoPendenciasRoute
  '/api/admin/conciliar-asaas': typeof ApiAdminConciliarAsaasRoute
  '/api/admin/cozinha-users': typeof ApiAdminCozinhaUsersRoute
  '/api/admin/cupons': typeof ApiAdminCuponsRoute
  '/api/admin/email': typeof ApiAdminEmailRoute
  '/api/admin/email-logs': typeof ApiAdminEmailLogsRoute
  '/api/admin/operacao-users': typeof ApiAdminOperacaoUsersRoute
  '/api/admin/operators': typeof ApiAdminOperatorsRoute
  '/api/admin/pedidos': typeof ApiAdminPedidosRoute
  '/api/admin/save-config': typeof ApiAdminSaveConfigRoute
  '/api/cozinha/pedidos': typeof ApiCozinhaPedidosRoute
  '/api/cozinha/token': typeof ApiCozinhaTokenRoute
  '/api/operacao/pedidos': typeof ApiOperacaoPedidosRoute
  '/api/operacao/token': typeof ApiOperacaoTokenRoute
  '/api/pedidos/editar-por-token': typeof ApiPedidosEditarPorTokenRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/mp-preference': typeof ApiPublicMpPreferenceRoute
  '/api/public/admin/pedidos': typeof ApiPublicAdminPedidosRoute
  '/api/public/asaas/charge': typeof ApiPublicAsaasChargeRoute
  '/api/public/asaas/webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/comprovante/$id': typeof ApiPublicComprovanteIdRoute
  '/api/public/cupom/validar': typeof ApiPublicCupomValidarRoute
  '/api/public/pagamento/$id': typeof ApiPublicPagamentoIdRoute
  '/api/public/pedido/$id': typeof ApiPublicPedidoIdRoute
  '/api/public/asaas/status/$id': typeof ApiPublicAsaasStatusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/checkout'
    | '/cozinha'
    | '/operacao'
    | '/pedido'
    | '/admin/dashboard'
    | '/api/disponibilidade'
    | '/pagar/$id'
    | '/pedidos/$token'
    | '/pedidos/novo'
    | '/sucesso/$id'
    | '/api/admin/arquivar-pedidos'
    | '/api/admin/conciliacao-pendencias'
    | '/api/admin/conciliar-asaas'
    | '/api/admin/cozinha-users'
    | '/api/admin/cupons'
    | '/api/admin/email'
    | '/api/admin/email-logs'
    | '/api/admin/operacao-users'
    | '/api/admin/operators'
    | '/api/admin/pedidos'
    | '/api/admin/save-config'
    | '/api/cozinha/pedidos'
    | '/api/cozinha/token'
    | '/api/operacao/pedidos'
    | '/api/operacao/token'
    | '/api/pedidos/editar-por-token'
    | '/api/public/meta-capi'
    | '/api/public/mp-preference'
    | '/api/public/admin/pedidos'
    | '/api/public/asaas/charge'
    | '/api/public/asaas/webhook'
    | '/api/public/comprovante/$id'
    | '/api/public/cupom/validar'
    | '/api/public/pagamento/$id'
    | '/api/public/pedido/$id'
    | '/api/public/asaas/status/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/checkout'
    | '/cozinha'
    | '/operacao'
    | '/pedido'
    | '/admin/dashboard'
    | '/api/disponibilidade'
    | '/pagar/$id'
    | '/pedidos/$token'
    | '/pedidos/novo'
    | '/sucesso/$id'
    | '/api/admin/arquivar-pedidos'
    | '/api/admin/conciliacao-pendencias'
    | '/api/admin/conciliar-asaas'
    | '/api/admin/cozinha-users'
    | '/api/admin/cupons'
    | '/api/admin/email'
    | '/api/admin/email-logs'
    | '/api/admin/operacao-users'
    | '/api/admin/operators'
    | '/api/admin/pedidos'
    | '/api/admin/save-config'
    | '/api/cozinha/pedidos'
    | '/api/cozinha/token'
    | '/api/operacao/pedidos'
    | '/api/operacao/token'
    | '/api/pedidos/editar-por-token'
    | '/api/public/meta-capi'
    | '/api/public/mp-preference'
    | '/api/public/admin/pedidos'
    | '/api/public/asaas/charge'
    | '/api/public/asaas/webhook'
    | '/api/public/comprovante/$id'
    | '/api/public/cupom/validar'
    | '/api/public/pagamento/$id'
    | '/api/public/pedido/$id'
    | '/api/public/asaas/status/$id'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/checkout'
    | '/cozinha'
    | '/operacao'
    | '/pedido'
    | '/admin/dashboard'
    | '/api/disponibilidade'
    | '/pagar/$id'
    | '/pedidos/$token'
    | '/pedidos/novo'
    | '/sucesso/$id'
    | '/api/admin/arquivar-pedidos'
    | '/api/admin/conciliacao-pendencias'
    | '/api/admin/conciliar-asaas'
    | '/api/admin/cozinha-users'
    | '/api/admin/cupons'
    | '/api/admin/email'
    | '/api/admin/email-logs'
    | '/api/admin/operacao-users'
    | '/api/admin/operators'
    | '/api/admin/pedidos'
    | '/api/admin/save-config'
    | '/api/cozinha/pedidos'
    | '/api/cozinha/token'
    | '/api/operacao/pedidos'
    | '/api/operacao/token'
    | '/api/pedidos/editar-por-token'
    | '/api/public/meta-capi'
    | '/api/public/mp-preference'
    | '/api/public/admin/pedidos'
    | '/api/public/asaas/charge'
    | '/api/public/asaas/webhook'
    | '/api/public/comprovante/$id'
    | '/api/public/cupom/validar'
    | '/api/public/pagamento/$id'
    | '/api/public/pedido/$id'
    | '/api/public/asaas/status/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CozinhaRoute: typeof CozinhaRoute
  OperacaoRoute: typeof OperacaoRoute
  PedidoRoute: typeof PedidoRoute
  ApiDisponibilidadeRoute: typeof ApiDisponibilidadeRoute
  PagarIdRoute: typeof PagarIdRoute
  PedidosTokenRoute: typeof PedidosTokenRoute
  PedidosNovoRoute: typeof PedidosNovoRoute
  SucessoIdRoute: typeof SucessoIdRoute
  ApiAdminArquivarPedidosRoute: typeof ApiAdminArquivarPedidosRoute
  ApiAdminConciliacaoPendenciasRoute: typeof ApiAdminConciliacaoPendenciasRoute
  ApiAdminConciliarAsaasRoute: typeof ApiAdminConciliarAsaasRoute
  ApiAdminCozinhaUsersRoute: typeof ApiAdminCozinhaUsersRoute
  ApiAdminCuponsRoute: typeof ApiAdminCuponsRoute
  ApiAdminEmailRoute: typeof ApiAdminEmailRoute
  ApiAdminEmailLogsRoute: typeof ApiAdminEmailLogsRoute
  ApiAdminOperacaoUsersRoute: typeof ApiAdminOperacaoUsersRoute
  ApiAdminOperatorsRoute: typeof ApiAdminOperatorsRoute
  ApiAdminPedidosRoute: typeof ApiAdminPedidosRoute
  ApiAdminSaveConfigRoute: typeof ApiAdminSaveConfigRoute
  ApiCozinhaPedidosRoute: typeof ApiCozinhaPedidosRoute
  ApiCozinhaTokenRoute: typeof ApiCozinhaTokenRoute
  ApiOperacaoPedidosRoute: typeof ApiOperacaoPedidosRoute
  ApiOperacaoTokenRoute: typeof ApiOperacaoTokenRoute
  ApiPedidosEditarPorTokenRoute: typeof ApiPedidosEditarPorTokenRoute
  ApiPublicMetaCapiRoute: typeof ApiPublicMetaCapiRoute
  ApiPublicMpPreferenceRoute: typeof ApiPublicMpPreferenceRoute
  ApiPublicAdminPedidosRoute: typeof ApiPublicAdminPedidosRoute
  ApiPublicAsaasChargeRoute: typeof ApiPublicAsaasChargeRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicComprovanteIdRoute: typeof ApiPublicComprovanteIdRoute
  ApiPublicCupomValidarRoute: typeof ApiPublicCupomValidarRoute
  ApiPublicPagamentoIdRoute: typeof ApiPublicPagamentoIdRoute
  ApiPublicPedidoIdRoute: typeof ApiPublicPedidoIdRoute
  ApiPublicAsaasStatusIdRoute: typeof ApiPublicAsaasStatusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cozinha': {
      id: '/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof CozinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso/$id': {
      id: '/sucesso/$id'
      path: '/sucesso/$id'
      fullPath: '/sucesso/$id'
      preLoaderRoute: typeof SucessoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/novo': {
      id: '/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof PedidosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$token': {
      id: '/pedidos/$token'
      path: '/pedidos/$token'
      fullPath: '/pedidos/$token'
      preLoaderRoute: typeof PedidosTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar/$id': {
      id: '/pagar/$id'
      path: '/pagar/$id'
      fullPath: '/pagar/$id'
      preLoaderRoute: typeof PagarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disponibilidade': {
      id: '/api/disponibilidade'
      path: '/api/disponibilidade'
      fullPath: '/api/disponibilidade'
      preLoaderRoute: typeof ApiDisponibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/mp-preference': {
      id: '/api/public/mp-preference'
      path: '/api/public/mp-preference'
      fullPath: '/api/public/mp-preference'
      preLoaderRoute: typeof ApiPublicMpPreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-capi': {
      id: '/api/public/meta-capi'
      path: '/api/public/meta-capi'
      fullPath: '/api/public/meta-capi'
      preLoaderRoute: typeof ApiPublicMetaCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pedidos/editar-por-token': {
      id: '/api/pedidos/editar-por-token'
      path: '/api/pedidos/editar-por-token'
      fullPath: '/api/pedidos/editar-por-token'
      preLoaderRoute: typeof ApiPedidosEditarPorTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operacao/token': {
      id: '/api/operacao/token'
      path: '/api/operacao/token'
      fullPath: '/api/operacao/token'
      preLoaderRoute: typeof ApiOperacaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operacao/pedidos': {
      id: '/api/operacao/pedidos'
      path: '/api/operacao/pedidos'
      fullPath: '/api/operacao/pedidos'
      preLoaderRoute: typeof ApiOperacaoPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cozinha/token': {
      id: '/api/cozinha/token'
      path: '/api/cozinha/token'
      fullPath: '/api/cozinha/token'
      preLoaderRoute: typeof ApiCozinhaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cozinha/pedidos': {
      id: '/api/cozinha/pedidos'
      path: '/api/cozinha/pedidos'
      fullPath: '/api/cozinha/pedidos'
      preLoaderRoute: typeof ApiCozinhaPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/save-config': {
      id: '/api/admin/save-config'
      path: '/api/admin/save-config'
      fullPath: '/api/admin/save-config'
      preLoaderRoute: typeof ApiAdminSaveConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pedidos': {
      id: '/api/admin/pedidos'
      path: '/api/admin/pedidos'
      fullPath: '/api/admin/pedidos'
      preLoaderRoute: typeof ApiAdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/operators': {
      id: '/api/admin/operators'
      path: '/api/admin/operators'
      fullPath: '/api/admin/operators'
      preLoaderRoute: typeof ApiAdminOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/operacao-users': {
      id: '/api/admin/operacao-users'
      path: '/api/admin/operacao-users'
      fullPath: '/api/admin/operacao-users'
      preLoaderRoute: typeof ApiAdminOperacaoUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-logs': {
      id: '/api/admin/email-logs'
      path: '/api/admin/email-logs'
      fullPath: '/api/admin/email-logs'
      preLoaderRoute: typeof ApiAdminEmailLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email': {
      id: '/api/admin/email'
      path: '/api/admin/email'
      fullPath: '/api/admin/email'
      preLoaderRoute: typeof ApiAdminEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cupons': {
      id: '/api/admin/cupons'
      path: '/api/admin/cupons'
      fullPath: '/api/admin/cupons'
      preLoaderRoute: typeof ApiAdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cozinha-users': {
      id: '/api/admin/cozinha-users'
      path: '/api/admin/cozinha-users'
      fullPath: '/api/admin/cozinha-users'
      preLoaderRoute: typeof ApiAdminCozinhaUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/conciliar-asaas': {
      id: '/api/admin/conciliar-asaas'
      path: '/api/admin/conciliar-asaas'
      fullPath: '/api/admin/conciliar-asaas'
      preLoaderRoute: typeof ApiAdminConciliarAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/conciliacao-pendencias': {
      id: '/api/admin/conciliacao-pendencias'
      path: '/api/admin/conciliacao-pendencias'
      fullPath: '/api/admin/conciliacao-pendencias'
      preLoaderRoute: typeof ApiAdminConciliacaoPendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/arquivar-pedidos': {
      id: '/api/admin/arquivar-pedidos'
      path: '/api/admin/arquivar-pedidos'
      fullPath: '/api/admin/arquivar-pedidos'
      preLoaderRoute: typeof ApiAdminArquivarPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pedido/$id': {
      id: '/api/public/pedido/$id'
      path: '/api/public/pedido/$id'
      fullPath: '/api/public/pedido/$id'
      preLoaderRoute: typeof ApiPublicPedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pagamento/$id': {
      id: '/api/public/pagamento/$id'
      path: '/api/public/pagamento/$id'
      fullPath: '/api/public/pagamento/$id'
      preLoaderRoute: typeof ApiPublicPagamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cupom/validar': {
      id: '/api/public/cupom/validar'
      path: '/api/public/cupom/validar'
      fullPath: '/api/public/cupom/validar'
      preLoaderRoute: typeof ApiPublicCupomValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/comprovante/$id': {
      id: '/api/public/comprovante/$id'
      path: '/api/public/comprovante/$id'
      fullPath: '/api/public/comprovante/$id'
      preLoaderRoute: typeof ApiPublicComprovanteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas/webhook': {
      id: '/api/public/asaas/webhook'
      path: '/api/public/asaas/webhook'
      fullPath: '/api/public/asaas/webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas/charge': {
      id: '/api/public/asaas/charge'
      path: '/api/public/asaas/charge'
      fullPath: '/api/public/asaas/charge'
      preLoaderRoute: typeof ApiPublicAsaasChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/pedidos': {
      id: '/api/public/admin/pedidos'
      path: '/api/public/admin/pedidos'
      fullPath: '/api/public/admin/pedidos'
      preLoaderRoute: typeof ApiPublicAdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas/status/$id': {
      id: '/api/public/asaas/status/$id'
      path: '/api/public/asaas/status/$id'
      fullPath: '/api/public/asaas/status/$id'
      preLoaderRoute: typeof ApiPublicAsaasStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CozinhaRoute: CozinhaRoute,
  OperacaoRoute: OperacaoRoute,
  PedidoRoute: PedidoRoute,
  ApiDisponibilidadeRoute: ApiDisponibilidadeRoute,
  PagarIdRoute: PagarIdRoute,
  PedidosTokenRoute: PedidosTokenRoute,
  PedidosNovoRoute: PedidosNovoRoute,
  SucessoIdRoute: SucessoIdRoute,
  ApiAdminArquivarPedidosRoute: ApiAdminArquivarPedidosRoute,
  ApiAdminConciliacaoPendenciasRoute: ApiAdminConciliacaoPendenciasRoute,
  ApiAdminConciliarAsaasRoute: ApiAdminConciliarAsaasRoute,
  ApiAdminCozinhaUsersRoute: ApiAdminCozinhaUsersRoute,
  ApiAdminCuponsRoute: ApiAdminCuponsRoute,
  ApiAdminEmailRoute: ApiAdminEmailRoute,
  ApiAdminEmailLogsRoute: ApiAdminEmailLogsRoute,
  ApiAdminOperacaoUsersRoute: ApiAdminOperacaoUsersRoute,
  ApiAdminOperatorsRoute: ApiAdminOperatorsRoute,
  ApiAdminPedidosRoute: ApiAdminPedidosRoute,
  ApiAdminSaveConfigRoute: ApiAdminSaveConfigRoute,
  ApiCozinhaPedidosRoute: ApiCozinhaPedidosRoute,
  ApiCozinhaTokenRoute: ApiCozinhaTokenRoute,
  ApiOperacaoPedidosRoute: ApiOperacaoPedidosRoute,
  ApiOperacaoTokenRoute: ApiOperacaoTokenRoute,
  ApiPedidosEditarPorTokenRoute: ApiPedidosEditarPorTokenRoute,
  ApiPublicMetaCapiRoute: ApiPublicMetaCapiRoute,
  ApiPublicMpPreferenceRoute: ApiPublicMpPreferenceRoute,
  ApiPublicAdminPedidosRoute: ApiPublicAdminPedidosRoute,
  ApiPublicAsaasChargeRoute: ApiPublicAsaasChargeRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicComprovanteIdRoute: ApiPublicComprovanteIdRoute,
  ApiPublicCupomValidarRoute: ApiPublicCupomValidarRoute,
  ApiPublicPagamentoIdRoute: ApiPublicPagamentoIdRoute,
  ApiPublicPedidoIdRoute: ApiPublicPedidoIdRoute,
  ApiPublicAsaasStatusIdRoute: ApiPublicAsaasStatusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
