/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidosTokenRouteImport } from './routes/pedidos.$token'
import { Route as ApiPublicMpPreferenceRouteImport } from './routes/api/public/mp-preference'
import { Route as ApiPublicMetaCapiRouteImport } from './routes/api/public/meta-capi'

const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosTokenRoute = PedidosTokenRouteImport.update({
  id: '/pedidos/$token',
  path: '/pedidos/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpPreferenceRoute = ApiPublicMpPreferenceRouteImport.update({
  id: '/api/public/mp-preference',
  path: '/api/public/mp-preference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaCapiRoute = ApiPublicMetaCapiRouteImport.update({
  id: '/api/public/meta-capi',
  path: '/api/public/meta-capi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/pedido': typeof PedidoRoute
  '/pedidos/$token': typeof PedidosTokenRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/mp-preference': typeof ApiPublicMpPreferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/pedido': typeof PedidoRoute
  '/pedidos/$token': typeof PedidosTokenRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/mp-preference': typeof ApiPublicMpPreferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/pedido': typeof PedidoRoute
  '/pedidos/$token': typeof PedidosTokenRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/mp-preference': typeof ApiPublicMpPreferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/checkout'
    | '/pedido'
    | '/pedidos/$token'
    | '/api/public/meta-capi'
    | '/api/public/mp-preference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/checkout'
    | '/pedido'
    | '/pedidos/$token'
    | '/api/public/meta-capi'
    | '/api/public/mp-preference'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/checkout'
    | '/pedido'
    | '/pedidos/$token'
    | '/api/public/meta-capi'
    | '/api/public/mp-preference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  PedidoRoute: typeof PedidoRoute
  PedidosTokenRoute: typeof PedidosTokenRoute
  ApiPublicMetaCapiRoute: typeof ApiPublicMetaCapiRoute
  ApiPublicMpPreferenceRoute: typeof ApiPublicMpPreferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$token': {
      id: '/pedidos/$token'
      path: '/pedidos/$token'
      fullPath: '/pedidos/$token'
      preLoaderRoute: typeof PedidosTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-preference': {
      id: '/api/public/mp-preference'
      path: '/api/public/mp-preference'
      fullPath: '/api/public/mp-preference'
      preLoaderRoute: typeof ApiPublicMpPreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-capi': {
      id: '/api/public/meta-capi'
      path: '/api/public/meta-capi'
      fullPath: '/api/public/meta-capi'
      preLoaderRoute: typeof ApiPublicMetaCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  PedidoRoute: PedidoRoute,
  PedidosTokenRoute: PedidosTokenRoute,
  ApiPublicMetaCapiRoute: ApiPublicMetaCapiRoute,
  ApiPublicMpPreferenceRoute: ApiPublicMpPreferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
