/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SucessoIdRouteImport } from './routes/sucesso.$id'
import { Route as PedidosTokenRouteImport } from './routes/pedidos.$token'
import { Route as ApiPublicMpPreferenceRouteImport } from './routes/api/public/mp-preference'
import { Route as ApiPublicMetaCapiRouteImport } from './routes/api/public/meta-capi'
import { Route as ApiPublicPagamentoIdRouteImport } from './routes/api/public/pagamento.$id'
import { Route as ApiPublicCupomValidarRouteImport } from './routes/api/public/cupom/validar'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas/webhook'
import { Route as ApiPublicAsaasChargeRouteImport } from './routes/api/public/asaas/charge'
import { Route as ApiPublicAdminPedidosRouteImport } from './routes/api/public/admin/pedidos'
import { Route as ApiPublicAsaasStatusIdRouteImport } from './routes/api/public/asaas/status.$id'
import { Route as ApiAdminSaveConfigRouteImport } from './routes/api/admin/save-config'
import { Route as ApiAdminCuponsRouteImport } from './routes/api/admin/cupons'

const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoIdRoute = SucessoIdRouteImport.update({
  id: '/sucesso/$id',
  path: '/sucesso/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosTokenRoute = PedidosTokenRouteImport.update({
  id: '/pedidos/$token',
  path: '/pedidos/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpPreferenceRoute = ApiPublicMpPreferenceRouteImport.update({
  id: '/api/public/mp-preference',
  path: '/api/public/mp-preference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaCapiRoute = ApiPublicMetaCapiRouteImport.update({
  id: '/api/public/meta-capi',
  path: '/api/public/meta-capi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPagamentoIdRoute = ApiPublicPagamentoIdRouteImport.update({
  id: '/api/public/pagamento/$id',
  path: '/api/public/pagamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCupomValidarRoute = ApiPublicCupomValidarRouteImport.update({
  id: '/api/public/cupom/validar',
  path: '/api/public/cupom/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas/webhook',
  path: '/api/public/asaas/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasChargeRoute = ApiPublicAsaasChargeRouteImport.update({
  id: '/api/public/asaas/charge',
  path: '/api/public/asaas/charge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminPedidosRoute = ApiPublicAdminPedidosRouteImport.update({
  id: '/api/public/admin/pedidos',
  path: '/api/public/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasStatusIdRoute = ApiPublicAsaasStatusIdRouteImport.update({
  id: '/api/public/asaas/status/$id',
  path: '/api/public/asaas/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSaveConfigRoute = ApiAdminSaveConfigRouteImport.update({
  id: '/api/admin/save-config',
  path: '/api/admin/save-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCuponsRoute = ApiAdminCuponsRouteImport.update({
  id: '/api/admin/cupons',
  path: '/api/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/pedido': typeof PedidoRoute
  '/pedidos/$token': typeof PedidosTokenRoute
  '/sucesso/$id': typeof SucessoIdRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/mp-preference': typeof ApiPublicMpPreferenceRoute
  '/api/public/admin/pedidos': typeof ApiPublicAdminPedidosRoute
  '/api/public/asaas/charge': typeof ApiPublicAsaasChargeRoute
  '/api/public/asaas/webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/cupom/validar': typeof ApiPublicCupomValidarRoute
  '/api/public/pagamento/$id': typeof ApiPublicPagamentoIdRoute
  '/api/public/asaas/status/$id': typeof ApiPublicAsaasStatusIdRoute
  '/api/admin/save-config': typeof ApiAdminSaveConfigRoute
  '/api/admin/cupons': typeof ApiAdminCuponsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/pedido': typeof PedidoRoute
  '/pedidos/$token': typeof PedidosTokenRoute
  '/sucesso/$id': typeof SucessoIdRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/mp-preference': typeof ApiPublicMpPreferenceRoute
  '/api/public/admin/pedidos': typeof ApiPublicAdminPedidosRoute
  '/api/public/asaas/charge': typeof ApiPublicAsaasChargeRoute
  '/api/public/asaas/webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/cupom/validar': typeof ApiPublicCupomValidarRoute
  '/api/public/pagamento/$id': typeof ApiPublicPagamentoIdRoute
  '/api/public/asaas/status/$id': typeof ApiPublicAsaasStatusIdRoute
  '/api/admin/save-config': typeof ApiAdminSaveConfigRoute
  '/api/admin/cupons': typeof ApiAdminCuponsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/pedido': typeof PedidoRoute
  '/pedidos/$token': typeof PedidosTokenRoute
  '/sucesso/$id': typeof SucessoIdRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/mp-preference': typeof ApiPublicMpPreferenceRoute
  '/api/public/admin/pedidos': typeof ApiPublicAdminPedidosRoute
  '/api/public/asaas/charge': typeof ApiPublicAsaasChargeRoute
  '/api/public/asaas/webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/cupom/validar': typeof ApiPublicCupomValidarRoute
  '/api/public/pagamento/$id': typeof ApiPublicPagamentoIdRoute
  '/api/public/asaas/status/$id': typeof ApiPublicAsaasStatusIdRoute
  '/api/admin/save-config': typeof ApiAdminSaveConfigRoute
  '/api/admin/cupons': typeof ApiAdminCuponsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/checkout'
    | '/pedido'
    | '/pedidos/$token'
    | '/sucesso/$id'
    | '/api/public/meta-capi'
    | '/api/public/mp-preference'
    | '/api/public/admin/pedidos'
    | '/api/public/asaas/charge'
    | '/api/public/asaas/webhook'
    | '/api/public/cupom/validar'
    | '/api/public/pagamento/$id'
    | '/api/public/asaas/status/$id'
    | '/api/admin/save-config'
    | '/api/admin/cupons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/checkout'
    | '/pedido'
    | '/pedidos/$token'
    | '/sucesso/$id'
    | '/api/public/meta-capi'
    | '/api/public/mp-preference'
    | '/api/public/admin/pedidos'
    | '/api/public/asaas/charge'
    | '/api/public/asaas/webhook'
    | '/api/public/cupom/validar'
    | '/api/public/pagamento/$id'
    | '/api/public/asaas/status/$id'
    | '/api/admin/save-config'
    | '/api/admin/cupons'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/checkout'
    | '/pedido'
    | '/pedidos/$token'
    | '/sucesso/$id'
    | '/api/public/meta-capi'
    | '/api/public/mp-preference'
    | '/api/public/admin/pedidos'
    | '/api/public/asaas/charge'
    | '/api/public/asaas/webhook'
    | '/api/public/cupom/validar'
    | '/api/public/pagamento/$id'
    | '/api/public/asaas/status/$id'
    | '/api/admin/save-config'
    | '/api/admin/cupons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  PedidoRoute: typeof PedidoRoute
  PedidosTokenRoute: typeof PedidosTokenRoute
  SucessoIdRoute: typeof SucessoIdRoute
  ApiPublicMetaCapiRoute: typeof ApiPublicMetaCapiRoute
  ApiPublicMpPreferenceRoute: typeof ApiPublicMpPreferenceRoute
  ApiPublicAdminPedidosRoute: typeof ApiPublicAdminPedidosRoute
  ApiPublicAsaasChargeRoute: typeof ApiPublicAsaasChargeRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicCupomValidarRoute: typeof ApiPublicCupomValidarRoute
  ApiPublicPagamentoIdRoute: typeof ApiPublicPagamentoIdRoute
  ApiPublicAsaasStatusIdRoute: typeof ApiPublicAsaasStatusIdRoute
  ApiAdminSaveConfigRoute: typeof ApiAdminSaveConfigRoute
  ApiAdminCuponsRoute: typeof ApiAdminCuponsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso/$id': {
      id: '/sucesso/$id'
      path: '/sucesso/$id'
      fullPath: '/sucesso/$id'
      preLoaderRoute: typeof SucessoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$token': {
      id: '/pedidos/$token'
      path: '/pedidos/$token'
      fullPath: '/pedidos/$token'
      preLoaderRoute: typeof PedidosTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-preference': {
      id: '/api/public/mp-preference'
      path: '/api/public/mp-preference'
      fullPath: '/api/public/mp-preference'
      preLoaderRoute: typeof ApiPublicMpPreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-capi': {
      id: '/api/public/meta-capi'
      path: '/api/public/meta-capi'
      fullPath: '/api/public/meta-capi'
      preLoaderRoute: typeof ApiPublicMetaCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pagamento/$id': {
      id: '/api/public/pagamento/$id'
      path: '/api/public/pagamento/$id'
      fullPath: '/api/public/pagamento/$id'
      preLoaderRoute: typeof ApiPublicPagamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cupom/validar': {
      id: '/api/public/cupom/validar'
      path: '/api/public/cupom/validar'
      fullPath: '/api/public/cupom/validar'
      preLoaderRoute: typeof ApiPublicCupomValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas/webhook': {
      id: '/api/public/asaas/webhook'
      path: '/api/public/asaas/webhook'
      fullPath: '/api/public/asaas/webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas/charge': {
      id: '/api/public/asaas/charge'
      path: '/api/public/asaas/charge'
      fullPath: '/api/public/asaas/charge'
      preLoaderRoute: typeof ApiPublicAsaasChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/pedidos': {
      id: '/api/public/admin/pedidos'
      path: '/api/public/admin/pedidos'
      fullPath: '/api/public/admin/pedidos'
      preLoaderRoute: typeof ApiPublicAdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas/status/$id': {
      id: '/api/public/asaas/status/$id'
      path: '/api/public/asaas/status/$id'
      fullPath: '/api/public/asaas/status/$id'
      preLoaderRoute: typeof ApiPublicAsaasStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/save-config': {
      id: '/api/admin/save-config'
      path: '/api/admin/save-config'
      fullPath: '/api/admin/save-config'
      preLoaderRoute: typeof ApiAdminSaveConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cupons': {
      id: '/api/admin/cupons'
      path: '/api/admin/cupons'
      fullPath: '/api/admin/cupons'
      preLoaderRoute: typeof ApiAdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  PedidoRoute: PedidoRoute,
  PedidosTokenRoute: PedidosTokenRoute,
  SucessoIdRoute: SucessoIdRoute,
  ApiPublicMetaCapiRoute: ApiPublicMetaCapiRoute,
  ApiPublicMpPreferenceRoute: ApiPublicMpPreferenceRoute,
  ApiPublicAdminPedidosRoute: ApiPublicAdminPedidosRoute,
  ApiPublicAsaasChargeRoute: ApiPublicAsaasChargeRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicCupomValidarRoute: ApiPublicCupomValidarRoute,
  ApiPublicPagamentoIdRoute: ApiPublicPagamentoIdRoute,
  ApiPublicAsaasStatusIdRoute: ApiPublicAsaasStatusIdRoute,
  ApiAdminSaveConfigRoute: ApiAdminSaveConfigRoute,
  ApiAdminCuponsRoute: ApiAdminCuponsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
